name: CD

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    name: "Publish Docker Image"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Docker Meta
      id: docker_meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/wipacrepo/wipac-disk-tracking
        tag-sha: true
        tag-semver: |
          {{major}}
          {{major}}.{{minor}}
          {{major}}.{{minor}}.{{patch}}
        tags: |
          type=ref,event=branch,branch=main,tag=main
          type=ref,event=branch,branch=main,tag=latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
